# Generated by Django 3.2.5 on 2023-11-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookclubmembers',
            name='club',
        ),
        migrations.RemoveField(
            model_name='bookclubmembers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookClub',
        ),
        migrations.DeleteModel(
            name='BookClubMembers',
        ),
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
